// Mirrors backend/constants.js

// Commands (RN → Worklet)
export const CMD = {
  NAVIGATE: 1,
  GET_STATUS: 2,
  LOAD_CATALOG: 10,
  LOAD_CATALOG_BEE: 16,
  INSTALL_APP: 11,
  UNINSTALL_APP: 12,
  LAUNCH_APP: 13,
  LIST_INSTALLED: 14,
  CHECK_UPDATES: 15,
  CREATE_SITE: 20,
  UPDATE_SITE: 21,
  PUBLISH_SITE: 22,
  UNPUBLISH_SITE: 23,
  LIST_SITES: 24,
  DELETE_SITE: 25,
  LOAD_TEMPLATE: 26,
  CLEAR_CACHE: 30,
  GET_IDENTITY: 31,
  GET_RELAYS: 40,
  SET_RELAYS: 41,
  SET_RELAY_ENABLED: 42,
  // User data (Phase 1 ticket 2)
  USERDATA_LIST_BOOKMARKS: 50,
  USERDATA_ADD_BOOKMARK: 51,
  USERDATA_REMOVE_BOOKMARK: 52,
  USERDATA_LIST_HISTORY: 53,
  USERDATA_ADD_HISTORY: 54,
  USERDATA_CLEAR_HISTORY: 55,
  USERDATA_GET_SETTINGS: 56,
  USERDATA_SET_SETTINGS: 57,
  USERDATA_GET_SESSION: 58,
  USERDATA_SAVE_SESSION: 59,
  USERDATA_IMPORT: 60,
  // Identity (Phase 1 ticket 3 + identity plan)
  IDENTITY_EXPORT_PHRASE: 70,
  IDENTITY_IMPORT_PHRASE: 71,
  IDENTITY_ROTATE: 72,
  IDENTITY_VALIDATE_PHRASE: 73,
  IDENTITY_SIGN: 74,
  // Profile + grants
  PROFILE_GET: 80,
  PROFILE_UPDATE: 81,
  PROFILE_CLEAR: 82,
  LOGIN_LIST_GRANTS: 83,
  LOGIN_REVOKE_GRANT: 84,
  LOGIN_REVOKE_ALL: 85,
  LOGIN_RESOLVE: 86,
  // Contacts
  CONTACTS_LIST: 90,
  CONTACTS_LOOKUP: 91,
  CONTACTS_ADD: 92,
  CONTACTS_UPDATE: 93,
  CONTACTS_REMOVE: 94,
  // Per-origin session tokens for HTTPS apps
  PEAR_SESSION: 95,
  BRIDGE: 200,
  STOP: 99,
} as const

// Events (Worklet → RN)
export const EVT = {
  READY: 100,
  PEER_COUNT: 101,
  ERROR: 102,
  INSTALL_PROGRESS: 103,
  SITE_PUBLISHED: 104,
  BOOT_PROGRESS: 105,
  /** A page called window.pear.login() — show the consent sheet. */
  LOGIN_REQUEST: 106,
} as const
