// Mirrors backend/constants.js

// Commands (RN → Worklet)
export const CMD = {
  NAVIGATE: 1,
  GET_STATUS: 2,
  LOAD_CATALOG: 10,
  LOAD_CATALOG_BEE: 16,
  INSTALL_APP: 11,
  UNINSTALL_APP: 12,
  LAUNCH_APP: 13,
  LIST_INSTALLED: 14,
  CHECK_UPDATES: 15,
  CREATE_SITE: 20,
  UPDATE_SITE: 21,
  PUBLISH_SITE: 22,
  UNPUBLISH_SITE: 23,
  LIST_SITES: 24,
  DELETE_SITE: 25,
  LOAD_TEMPLATE: 26,
  CLEAR_CACHE: 30,
  GET_IDENTITY: 31,
  GET_RELAYS: 40,
  SET_RELAYS: 41,
  SET_RELAY_ENABLED: 42,
  // User data (Phase 1 ticket 2)
  USERDATA_LIST_BOOKMARKS: 50,
  USERDATA_ADD_BOOKMARK: 51,
  USERDATA_REMOVE_BOOKMARK: 52,
  USERDATA_LIST_HISTORY: 53,
  USERDATA_ADD_HISTORY: 54,
  USERDATA_CLEAR_HISTORY: 55,
  USERDATA_GET_SETTINGS: 56,
  USERDATA_SET_SETTINGS: 57,
  USERDATA_GET_SESSION: 58,
  USERDATA_SAVE_SESSION: 59,
  USERDATA_IMPORT: 60,
  // Identity (Phase 1 ticket 3)
  IDENTITY_EXPORT_PHRASE: 70,
  IDENTITY_IMPORT_PHRASE: 71,
  IDENTITY_ROTATE: 72,
  IDENTITY_VALIDATE_PHRASE: 73,
  BRIDGE: 200,
  STOP: 99,
} as const

// Events (Worklet → RN)
export const EVT = {
  READY: 100,
  PEER_COUNT: 101,
  ERROR: 102,
  INSTALL_PROGRESS: 103,
  SITE_PUBLISHED: 104,
  BOOT_PROGRESS: 105,
} as const
